const fs=require('fs'),path=require('path');
const config=JSON.parse(fs.readFileSync('content/nivel2/legal.json','utf8'));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const css=`:root{color-scheme:light}*{box-sizing:border-box}body{margin:0;background:#faf7f5;color:#302b2e;font:400 16px/1.8 Montserrat,Arial,sans-serif}main{max-width:850px;margin:auto;padding:36px 24px 64px}h1,h2{font-family:Lora,Georgia,serif;font-weight:500;line-height:1.35}h1{font-size:30px}h2{font-size:22px;margin-top:32px}a{color:#70265f;text-underline-offset:3px}label{display:block;margin:16px 0}input,select{display:block;width:100%;padding:12px;border:1px solid #d4c8d0;border-radius:9px;font:inherit;background:white}button{border:0;border-radius:999px;padding:13px 24px;background:#ac0089;color:white;font:600 15px Montserrat,Arial,sans-serif;cursor:pointer}button:disabled{opacity:.6}small{font-size:13px}footer{border-top:1px solid #d4c8d0;margin-top:36px;padding-top:24px}.hp{display:none}@media(max-width:600px){h1{font-size:25px}h2{font-size:20px}body{font-size:15px}main{padding:24px 22px 48px}}`;
function page(title,body,script=''){return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · EPI</title><link href="https://fonts.googleapis.com/css2?family=Lora:wght@400;500&family=Montserrat:wght@400;500;600&display=swap" rel="stylesheet"><style>${css}</style></head><body><main><a href="/inspiraccion/nivel-2/">← Volver a InspirAcción Nivel 2</a><h1>${esc(title)}</h1>${body}<footer>Contacto de la Escuela: <a href="mailto:${config.contacto}">${config.contacto}</a><br><a href="${config.reglamentoUrl}">Reglamento Interno y Términos de Participación</a> · <a href="/arrepentimiento/">Botón de Arrepentimiento</a></footer></main>${script}</body></html>`;}
function write(route,html){const file=path.join(route,'index.html');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,html);}
const raw=fs.readFileSync('content/nivel2/reglamento-2026-09-18.txt','utf8');
const paras=raw.split(/\r?\n/).filter(s=>s.trim()).map(s=>/^\d+\. /.test(s)?`<h2>${esc(s)}</h2>`:`<p>${esc(s)}</p>`).join('\n');
write('legal/reglamento-interno',page('Reglamento Interno y Términos de Participación',`<small>Versión ${config.reglamentoVersion}</small>${paras}`));
write('legal/reglamento-interno/'+config.reglamentoVersion,page('Reglamento Interno y Términos de Participación',`<small>Versión ${config.reglamentoVersion}</small>${paras}`));
write('legal/inspiraccion-nivel-2-g4',page('Condiciones particulares · InspirAcción Nivel 2 · Generación 4',`<p>Cursada: enero y febrero de 2027. Duración: dos meses. Requisito: certificado de InspirAcción Nivel 1.</p><h2>Valores y formas de pago</h2><p>Hasta el 15/10/2026 inclusive: USD 300, con una reserva de USD 150. Desde el 16/10/2026 hasta el 05/11/2026 inclusive: USD 350, con una reserva de USD 175. El saldo restante debe abonarse hasta el 05/01/2027. Después del 05/11/2026: USD 400, pago completo. PayPal tiene un 5% de recargo. Otras monedas y condiciones especiales se consultan con el equipo.</p><h2>Revocación y cancelación</h2><p>El derecho legal de revocación y su plazo aplicable se informan en la sección 13 del <a href="${config.reglamentoUrl}">Reglamento Interno y Términos de Participación</a>.</p><p>${esc(config.cancelacion)}</p><p><a href="/arrepentimiento/">Botón de Arrepentimiento</a></p>`));
write('arrepentimiento',page('Botón de Arrepentimiento',`<p>Solicitá la revocación de tu contratación. No necesitás iniciar sesión ni indicar un motivo.</p><form id="revocation-form"><label>Nombre y apellido<input name="name" autocomplete="name" maxlength="150" required></label><label>Documento (DNI o pasaporte)<input name="document" maxlength="40" required></label><label>Email<input name="email" type="email" autocomplete="email" maxlength="200" required></label><label>Programa<input name="program" maxlength="150" required></label><label>Fecha de inscripción<input name="enrollmentDate" type="date" required></label><label class="hp" aria-hidden="true">Dejar vacío<input name="website" tabindex="-1" autocomplete="off"></label><button type="submit">Enviar solicitud de arrepentimiento</button><p id="request-status" role="status" aria-live="polite"></p></form><p>El pedido queda registrado al confirmarse el envío. Recibirás un código de gestión y una constancia en tu correo. El reintegro, cuando corresponda, se coordina con la Escuela.</p>`, '<script src="/arrepentimiento/form.js"></script>'));
console.log('Reglamento literal, condiciones particulares y formulario generados.');
